 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b57111f255'
down_revision = 'ab5e080a4a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_lov',
    sa.Column('lov_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=30), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('lov_id'),
    schema='smarttutor'
    )
    op.create_table('st_chapter',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subchapter_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=30), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['smarttutor.st_lov.lov_id'], ),
    sa.PrimaryKeyConstraint('chapter_id'),
    schema='smarttutor'
    )
    op.add_column('st_answers', sa.Column('created_by', sa.String(length=30), nullable=True))
    op.add_column('st_answers', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('st_answers', sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('st_answers', sa.Column('modified_by', sa.String(length=30), nullable=True))
    
    op.drop_constraint(op.f('st_answers_question_id_fkey'), 'st_answers', type_='foreignkey')
    op.create_foreign_key(None, 'st_answers', 'st_questions', ['question_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.add_column('st_questions', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('level_no', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('medium_id', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('subchapter_id', sa.Integer(), nullable=True))
    op.add_column('st_questions', sa.Column('language_translation', sa.String(length=255), nullable=True))
    op.add_column('st_questions', sa.Column('created_by', sa.String(length=30), nullable=True))
    op.add_column('st_questions', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('st_questions', sa.Column('modified_by', sa.String(length=30), nullable=True))
    op.add_column('st_questions', sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.create_foreign_key(None, 'st_questions', 'st_questions', ['parent_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['class_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['subchapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['medium_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['subject_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_column('st_questions', 'subject')
    op.add_column('st_userroles', sa.Column('created_by', sa.String(length=30), nullable=True))
    op.add_column('st_userroles', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('st_userroles', sa.Column('modified_by', sa.String(length=30), nullable=True))
    op.add_column('st_userroles', sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('st_users', sa.Column('created_by', sa.String(length=30), nullable=True))
    op.add_column('st_users', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('st_users', sa.Column('modified_by', sa.String(length=30), nullable=True))
    op.add_column('st_users', sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.drop_constraint(op.f('st_users_role_id_fkey'), 'st_users', type_='foreignkey')
    op.create_foreign_key(None, 'st_users', 'st_userroles', ['role_id'], ['role_id'], source_schema='smarttutor', referent_schema='smarttutor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'st_users', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_users_role_id_fkey'), 'st_users', 'st_userroles', ['role_id'], ['role_id'])
    op.drop_column('st_users', 'modified_on')
    op.drop_column('st_users', 'modified_by')
    op.drop_column('st_users', 'created_on')
    op.drop_column('st_users', 'created_by')
    op.drop_column('st_userroles', 'modified_on')
    op.drop_column('st_userroles', 'modified_by')
    op.drop_column('st_userroles', 'created_on')
    op.drop_column('st_userroles', 'created_by')
    op.add_column('st_questions', sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_column('st_questions', 'modified_on')
    op.drop_column('st_questions', 'modified_by')
    op.drop_column('st_questions', 'created_on')
    op.drop_column('st_questions', 'created_by')
    op.drop_column('st_questions', 'language_translation')
    op.drop_column('st_questions', 'subchapter_id')
    op.drop_column('st_questions', 'chapter_id')
    op.drop_column('st_questions', 'medium_id')
    op.drop_column('st_questions', 'subject_id')
    op.drop_column('st_questions', 'class_id')
    op.drop_column('st_questions', 'level_no')
    op.drop_column('st_questions', 'parent_id')
    op.drop_constraint(None, 'st_answers', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_answers_question_id_fkey'), 'st_answers', 'st_questions', ['question_id'], ['question_id'])
    op.drop_column('st_answers', 'modified_on')
    op.drop_column('st_answers', 'modified_by')
    op.drop_column('st_answers', 'created_on')
    op.drop_column('st_answers', 'created_by')
    op.drop_table('st_chapter', schema='smarttutor')
    op.drop_table('st_lov', schema='smarttutor')
    # ### end Alembic commands ###