"""fix chapter tables

Revision ID: 4e98b5b3b61d
Revises: 40b57111f255
Create Date: 2026-08-25 12:12:50.196725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e98b5b3b61d'
down_revision = '40b57111f255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_chapter',
    sa.Column('chapter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subchapter_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=30), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('board_lov_id', sa.Integer(), nullable=False),
    sa.Column('class_lov_id', sa.Integer(), nullable=False),
    sa.Column('subject_lov_id', sa.Integer(), nullable=False),
    sa.Column('chapter_no', sa.String(length=10), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('level_no', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_lov_id'], ['smarttutor.st_lov.lov_id'], ),
    sa.ForeignKeyConstraint(['class_lov_id'], ['smarttutor.st_lov.lov_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['smarttutor.st_lov.lov_id'], ),
    sa.ForeignKeyConstraint(['subject_lov_id'], ['smarttutor.st_lov.lov_id'], ),
    sa.PrimaryKeyConstraint('chapter_id'),
    schema='smarttutor'
    )
    op.create_table('st_subchapter',
    sa.Column('subchapter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=30), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subchapter_no', sa.String(length=10), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('level_no', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['smarttutor.st_chapter.chapter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subchapter_id'),
    schema='smarttutor'
    )
    op.drop_constraint(op.f('st_answers_question_id_fkey'), 'st_answers', type_='foreignkey')
    op.create_foreign_key(None, 'st_answers', 'st_questions', ['question_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_constraint(op.f('st_questions_parent_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_medium_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_class_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_subject_id_fkey'), 'st_questions', type_='foreignkey')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['subchapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['medium_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['class_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_questions', ['parent_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['subject_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_constraint(op.f('st_users_role_id_fkey'), 'st_users', type_='foreignkey')
    op.create_foreign_key(None, 'st_users', 'st_userroles', ['role_id'], ['role_id'], source_schema='smarttutor', referent_schema='smarttutor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'st_users', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_users_role_id_fkey'), 'st_users', 'st_userroles', ['role_id'], ['role_id'])
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_questions_subject_id_fkey'), 'st_questions', 'st_lov', ['subject_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_class_id_fkey'), 'st_questions', 'st_lov', ['class_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_medium_id_fkey'), 'st_questions', 'st_lov', ['medium_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_parent_id_fkey'), 'st_questions', 'st_questions', ['parent_id'], ['question_id'])
    op.drop_constraint(None, 'st_answers', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_answers_question_id_fkey'), 'st_answers', 'st_questions', ['question_id'], ['question_id'])
    op.drop_table('st_subchapter', schema='smarttutor')
    op.drop_table('st_chapter', schema='smarttutor')
    # ### end Alembic commands ###