"""fix chapter tables

Revision ID: 53bd8e984554
Revises: 523a787b4074
Create Date: 2026-08-25 12:33:33.124878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bd8e984554'
down_revision = '523a787b4074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('st_answers_question_id_fkey'), 'st_answers', type_='foreignkey')
    op.create_foreign_key(None, 'st_answers', 'st_questions', ['question_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.add_column('st_chapter', sa.Column('medium_lov_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('st_chapter_subject_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.drop_constraint(op.f('st_chapter_board_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.drop_constraint(op.f('st_chapter_class_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['subject_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['class_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['board_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['medium_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_constraint(op.f('st_questions_subject_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_class_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_subchapter_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_parent_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_chapter_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_medium_id_fkey'), 'st_questions', type_='foreignkey')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['medium_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_questions', ['parent_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['subchapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['class_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['subject_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_constraint(op.f('st_subchapter_chapter_id_fkey'), 'st_subchapter', type_='foreignkey')
    op.create_foreign_key(None, 'st_subchapter', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor', ondelete='CASCADE')
    op.drop_constraint(op.f('st_users_role_id_fkey'), 'st_users', type_='foreignkey')
    op.create_foreign_key(None, 'st_users', 'st_userroles', ['role_id'], ['role_id'], source_schema='smarttutor', referent_schema='smarttutor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'st_users', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_users_role_id_fkey'), 'st_users', 'st_userroles', ['role_id'], ['role_id'])
    op.drop_constraint(None, 'st_subchapter', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_subchapter_chapter_id_fkey'), 'st_subchapter', 'st_chapter', ['chapter_id'], ['chapter_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_questions_medium_id_fkey'), 'st_questions', 'st_lov', ['medium_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_chapter_id_fkey'), 'st_questions', 'st_chapter', ['chapter_id'], ['chapter_id'])
    op.create_foreign_key(op.f('st_questions_parent_id_fkey'), 'st_questions', 'st_questions', ['parent_id'], ['question_id'])
    op.create_foreign_key(op.f('st_questions_subchapter_id_fkey'), 'st_questions', 'st_chapter', ['subchapter_id'], ['chapter_id'])
    op.create_foreign_key(op.f('st_questions_class_id_fkey'), 'st_questions', 'st_lov', ['class_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_subject_id_fkey'), 'st_questions', 'st_lov', ['subject_id'], ['lov_id'])
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_chapter_class_lov_id_fkey'), 'st_chapter', 'st_lov', ['class_lov_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_chapter_board_lov_id_fkey'), 'st_chapter', 'st_lov', ['board_lov_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_chapter_subject_lov_id_fkey'), 'st_chapter', 'st_lov', ['subject_lov_id'], ['lov_id'])
    op.drop_column('st_chapter', 'medium_lov_id')
    op.drop_constraint(None, 'st_answers', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_answers_question_id_fkey'), 'st_answers', 'st_questions', ['question_id'], ['question_id'])
    # ### end Alembic commands ###