"""init schema

Revision ID: ab5e080a4a10
Revises: 
Create Date: 2026-08-07 16:31:28.789687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5e080a4a10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('question_id'),
    schema='smarttutor'
    )
    op.create_table('st_userroles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name'),
    schema='smarttutor'
    )
    op.create_table('st_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['smarttutor.st_questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id'),
    schema='smarttutor'
    )
    op.create_table('st_lov',
    sa.Column('lov_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),     
    sa.Column('value', sa.String(length=255), nullable=False), 
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.UniqueConstraint('type', 'value'),
    sa.PrimaryKeyConstraint('lov_id'),
    schema='smarttutor'
    )
    op.create_table('st_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('user_device', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['smarttutor.st_userroles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('username'),
    schema='smarttutor'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('st_users', schema='smarttutor')
    op.drop_table('st_lov', schema='smarttutor')
    op.drop_table('st_answers', schema='smarttutor')
    op.drop_table('st_userroles', schema='smarttutor')
    op.drop_table('st_questions', schema='smarttutor')
    # ### end Alembic commands ###