"""add glossary tables

Revision ID: c19195230556
Revises: ad358c33cea7
Create Date: 2026-10-02 14:54:28.583487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c19195230556'
down_revision = 'ad358c33cea7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_word', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='smarttutor'
    )
    op.create_index(op.f('ix_smarttutor_glossary_terms_english_word'), 'glossary_terms', ['english_word'], unique=True, schema='smarttutor')
    op.create_table('glossary_term_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('translated_word', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['smarttutor.glossary_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'language_code', name='uq_term_lang'),
    schema='smarttutor'
    )
    op.create_index(op.f('ix_smarttutor_glossary_term_translations_language_code'), 'glossary_term_translations', ['language_code'], unique=False, schema='smarttutor')
    op.create_index(op.f('ix_smarttutor_glossary_term_translations_term_id'), 'glossary_term_translations', ['term_id'], unique=False, schema='smarttutor')
    op.drop_constraint(op.f('chapter_translations_chapter_id_fkey'), 'chapter_translations', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_translations', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor', ondelete='CASCADE')
    op.alter_column('question_translations', 'question_text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('question_translations', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('question_translations', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('question_translations_question_id_fkey'), 'question_translations', type_='foreignkey')
    op.create_foreign_key(None, 'question_translations', 'st_questions', ['question_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor', ondelete='CASCADE')
    op.drop_constraint(op.f('st_answers_question_id_fkey'), 'st_answers', type_='foreignkey')
    op.create_foreign_key(None, 'st_answers', 'st_questions', ['question_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_constraint(op.f('st_chapter_class_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.drop_constraint(op.f('st_chapter_board_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.drop_constraint(op.f('st_chapter_medium_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.drop_constraint(op.f('st_chapter_subject_lov_id_fkey'), 'st_chapter', type_='foreignkey')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['class_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['medium_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['subject_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_chapter', 'st_lov', ['board_lov_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.alter_column('st_questions', 'language_translation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('st_questions_subject_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_parent_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_class_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_chapter_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_subchapter_id_fkey'), 'st_questions', type_='foreignkey')
    op.drop_constraint(op.f('st_questions_medium_id_fkey'), 'st_questions', type_='foreignkey')
    op.create_foreign_key(None, 'st_questions', 'st_questions', ['parent_id'], ['question_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['class_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['subchapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['medium_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.create_foreign_key(None, 'st_questions', 'st_lov', ['subject_id'], ['lov_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.drop_constraint(op.f('st_subchapter_chapter_id_fkey'), 'st_subchapter', type_='foreignkey')
    op.create_foreign_key(None, 'st_subchapter', 'st_chapter', ['chapter_id'], ['chapter_id'], source_schema='smarttutor', referent_schema='smarttutor', ondelete='CASCADE')
    op.drop_constraint(op.f('st_users_role_id_fkey'), 'st_users', type_='foreignkey')
    op.create_foreign_key(None, 'st_users', 'st_userroles', ['role_id'], ['role_id'], source_schema='smarttutor', referent_schema='smarttutor')
    op.alter_column('subchapter_translations', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subchapter_translations', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('subchapter_translations_subchapter_id_fkey'), 'subchapter_translations', type_='foreignkey')
    op.create_foreign_key(None, 'subchapter_translations', 'st_subchapter', ['subchapter_id'], ['subchapter_id'], source_schema='smarttutor', referent_schema='smarttutor', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'subchapter_translations', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('subchapter_translations_subchapter_id_fkey'), 'subchapter_translations', 'st_subchapter', ['subchapter_id'], ['subchapter_id'], ondelete='CASCADE')
    op.alter_column('subchapter_translations', 'modified_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subchapter_translations', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_users', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_users_role_id_fkey'), 'st_users', 'st_userroles', ['role_id'], ['role_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_subchapter', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_subchapter_chapter_id_fkey'), 'st_subchapter', 'st_chapter', ['chapter_id'], ['chapter_id'], ondelete='CASCADE')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_questions', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_questions_medium_id_fkey'), 'st_questions', 'st_lov', ['medium_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_subchapter_id_fkey'), 'st_questions', 'st_subchapter', ['subchapter_id'], ['subchapter_id'])
    op.create_foreign_key(op.f('st_questions_chapter_id_fkey'), 'st_questions', 'st_chapter', ['chapter_id'], ['chapter_id'])
    op.create_foreign_key(op.f('st_questions_class_id_fkey'), 'st_questions', 'st_lov', ['class_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_questions_parent_id_fkey'), 'st_questions', 'st_questions', ['parent_id'], ['question_id'])
    op.create_foreign_key(op.f('st_questions_subject_id_fkey'), 'st_questions', 'st_lov', ['subject_id'], ['lov_id'])
    op.alter_column('st_questions', 'language_translation',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_chapter', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_chapter_subject_lov_id_fkey'), 'st_chapter', 'st_lov', ['subject_lov_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_chapter_medium_lov_id_fkey'), 'st_chapter', 'st_lov', ['medium_lov_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_chapter_board_lov_id_fkey'), 'st_chapter', 'st_lov', ['board_lov_id'], ['lov_id'])
    op.create_foreign_key(op.f('st_chapter_class_lov_id_fkey'), 'st_chapter', 'st_lov', ['class_lov_id'], ['lov_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'st_answers', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('st_answers_question_id_fkey'), 'st_answers', 'st_questions', ['question_id'], ['question_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'question_translations', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('question_translations_question_id_fkey'), 'question_translations', 'st_questions', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.alter_column('question_translations', 'modified_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('question_translations', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('question_translations', 'question_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'chapter_translations', schema='smarttutor', type_='foreignkey')
    op.create_foreign_key(op.f('chapter_translations_chapter_id_fkey'), 'chapter_translations', 'st_chapter', ['chapter_id'], ['chapter_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_smarttutor_glossary_term_translations_term_id'), table_name='glossary_term_translations', schema='smarttutor')
    op.drop_index(op.f('ix_smarttutor_glossary_term_translations_language_code'), table_name='glossary_term_translations', schema='smarttutor')
    op.drop_table('glossary_term_translations', schema='smarttutor')
    op.drop_index(op.f('ix_smarttutor_glossary_terms_english_word'), table_name='glossary_terms', schema='smarttutor')
    op.drop_table('glossary_terms', schema='smarttutor')
    # ### end Alembic commands ###